version: '3.9'

services:
  go-server:
    build:
      context: ./server
    container_name: rest-server
    hostname: rest-server
    env_file:
      - .env
    networks:
      - mynet
    ports:
      - 3000:3000
    depends_on:
      - mongo
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - ./server:/app

  # postgresdb:
  #   image: postgres:latest
  #   container_name: postgres_container
  #   environment:
  #     - POSTGRES_USER=${DB_USER}
  #     - POSTGRES_PASSWORD=${DB_PASSWORD}
  #     - POSTGRES_DB=${DB_NAME}
  #     - DATABASE_HOST=${DB_HOST}
  #   ports:
  #     - '1234:5432'
  #   volumes:
  #     - ./pg_data:/var/lib/postgresql/data
  #   networks:
  #     - mynet

  mongo:
    image: mongo:latest
    ports:
      - 3003:3003
    expose:
      - 3003
    restart: always
    container_name: mongo
    command: mongod --port=3003 --logpath /data/logs/mongolog.log --dbpath=/data/db
    env_file:
      - .env
    volumes:
      - mongo-data:/data/db
      - mongo-data:/data/logs
    networks:
      - mynet
    

volumes:
  pg_data:
  mongo-data:
    driver: local

networks:
  mynet:
    driver: bridge