database:
  host: ${DB_HOST}
  port: ${DB_PORT}
  dbname: ${DB_NAME}
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  migration: true

mongodb:
  mongo_uri: ${MONGO_URI}

extension:
  master_generator: true
  cors_enabled: true
  security_enabled: true

log:
  request_log_format: ${remote_ip} ${account_name} ${uri} ${method} ${status}

staticcontents:
  enabled: true

swagger:
  enabled: true
  path: /swagger/.*

security:
  auth_path:
    - /api/.*
  exclude_path:
    - /swagger/.*
    - /api/auth/login$
    - /api/auth/logout$
    - /api/health$
  user_path:
    - /api/.*
  admin_path:
    - /api/.*

port: ${PORT}
